import type { GraphNode, GraphEdge, GraphGroup } from '@/types'
import { DEFAULT_NODE_STYLE, DEFAULT_EDGE_STYLE } from '@/types'

export interface TemplateData {
  id: string
  name: string
  description: string
  nodes: GraphNode[]
  edges: GraphEdge[]
  groups: GraphGroup[]
}

const flowchart: TemplateData = {
  id: 'tpl-flowchart',
  name: '流程图',
  description: '基本流程图模板，包含开始、处理、判断和结束节点',
  nodes: [
    {
      id: 'tpl-flowchart-1',
      label: '开始',
      x: 240,
      y: 20,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#22c55e', strokeColor: '#15803d' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-flowchart-2',
      label: '处理1',
      x: 240,
      y: 120,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#3b82f6', strokeColor: '#1e40af' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-flowchart-3',
      label: '判断',
      x: 240,
      y: 220,
      width: 120,
      height: 60,
      shape: 'diamond',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#f59e0b', strokeColor: '#b45309' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-flowchart-4',
      label: '处理2',
      x: 240,
      y: 320,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#3b82f6', strokeColor: '#1e40af' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-flowchart-5',
      label: '结束',
      x: 240,
      y: 420,
      width: 120,
      height: 60,
      shape: 'roundedRect',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#ef4444', strokeColor: '#b91c1c' },
      data: {},
      zIndex: 0,
    },
  ],
  edges: [
    { id: 'tpl-flowchart-e1', sourceId: 'tpl-flowchart-1', targetId: 'tpl-flowchart-2', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-flowchart-e2', sourceId: 'tpl-flowchart-2', targetId: 'tpl-flowchart-3', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-flowchart-e3', sourceId: 'tpl-flowchart-3', targetId: 'tpl-flowchart-4', label: '是', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-flowchart-e4', sourceId: 'tpl-flowchart-4', targetId: 'tpl-flowchart-5', style: { ...DEFAULT_EDGE_STYLE } },
  ],
  groups: [],
}

const classDiagram: TemplateData = {
  id: 'tpl-class-diagram',
  name: '类图',
  description: '面向对象类图模板，展示继承关系',
  nodes: [
    {
      id: 'tpl-class-1',
      label: 'Animal',
      x: 200,
      y: 20,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#8b5cf6', strokeColor: '#6d28d9' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-class-2',
      label: 'Dog',
      x: 80,
      y: 160,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#3b82f6', strokeColor: '#1e40af' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-class-3',
      label: 'Cat',
      x: 320,
      y: 160,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#3b82f6', strokeColor: '#1e40af' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-class-4',
      label: 'Pet',
      x: 200,
      y: 300,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#10b981', strokeColor: '#047857' },
      data: {},
      zIndex: 0,
    },
  ],
  edges: [
    { id: 'tpl-class-e1', sourceId: 'tpl-class-2', targetId: 'tpl-class-1', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-class-e2', sourceId: 'tpl-class-3', targetId: 'tpl-class-1', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-class-e3', sourceId: 'tpl-class-2', targetId: 'tpl-class-4', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-class-e4', sourceId: 'tpl-class-3', targetId: 'tpl-class-4', style: { ...DEFAULT_EDGE_STYLE } },
  ],
  groups: [],
}

const erDiagram: TemplateData = {
  id: 'tpl-er-diagram',
  name: 'ER图',
  description: '实体关系图模板，展示数据模型关系',
  nodes: [
    {
      id: 'tpl-er-1',
      label: '用户',
      x: 80,
      y: 80,
      width: 120,
      height: 60,
      shape: 'ellipse',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#3b82f6', strokeColor: '#1e40af' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-er-2',
      label: '订单',
      x: 320,
      y: 80,
      width: 120,
      height: 60,
      shape: 'ellipse',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#f59e0b', strokeColor: '#b45309' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-er-3',
      label: '商品',
      x: 320,
      y: 240,
      width: 120,
      height: 60,
      shape: 'ellipse',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#10b981', strokeColor: '#047857' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-er-4',
      label: '类别',
      x: 80,
      y: 240,
      width: 120,
      height: 60,
      shape: 'ellipse',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#8b5cf6', strokeColor: '#6d28d9' },
      data: {},
      zIndex: 0,
    },
  ],
  edges: [
    { id: 'tpl-er-e1', sourceId: 'tpl-er-1', targetId: 'tpl-er-2', label: '下单', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-er-e2', sourceId: 'tpl-er-2', targetId: 'tpl-er-3', label: '包含', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-er-e3', sourceId: 'tpl-er-3', targetId: 'tpl-er-4', label: '属于', style: { ...DEFAULT_EDGE_STYLE } },
  ],
  groups: [],
}

const networkTopology: TemplateData = {
  id: 'tpl-network-topology',
  name: '网络拓扑',
  description: '网络拓扑图模板，展示网络设备连接关系',
  nodes: [
    {
      id: 'tpl-net-1',
      label: '路由器',
      x: 240,
      y: 20,
      width: 120,
      height: 60,
      shape: 'hexagon',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#f59e0b', strokeColor: '#b45309' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-net-2',
      label: '交换机',
      x: 240,
      y: 140,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#3b82f6', strokeColor: '#1e40af' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-net-3',
      label: '服务器1',
      x: 80,
      y: 260,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#10b981', strokeColor: '#047857' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-net-4',
      label: '服务器2',
      x: 400,
      y: 260,
      width: 120,
      height: 60,
      shape: 'rectangle',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#10b981', strokeColor: '#047857' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-net-5',
      label: '终端1',
      x: 80,
      y: 380,
      width: 120,
      height: 60,
      shape: 'ellipse',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#8b5cf6', strokeColor: '#6d28d9' },
      data: {},
      zIndex: 0,
    },
    {
      id: 'tpl-net-6',
      label: '终端2',
      x: 400,
      y: 380,
      width: 120,
      height: 60,
      shape: 'ellipse',
      style: { ...DEFAULT_NODE_STYLE, fillColor: '#8b5cf6', strokeColor: '#6d28d9' },
      data: {},
      zIndex: 0,
    },
  ],
  edges: [
    { id: 'tpl-net-e1', sourceId: 'tpl-net-1', targetId: 'tpl-net-2', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-net-e2', sourceId: 'tpl-net-2', targetId: 'tpl-net-3', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-net-e3', sourceId: 'tpl-net-2', targetId: 'tpl-net-4', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-net-e4', sourceId: 'tpl-net-3', targetId: 'tpl-net-5', style: { ...DEFAULT_EDGE_STYLE } },
    { id: 'tpl-net-e5', sourceId: 'tpl-net-4', targetId: 'tpl-net-6', style: { ...DEFAULT_EDGE_STYLE } },
  ],
  groups: [],
}

export const templates: TemplateData[] = [flowchart, classDiagram, erDiagram, networkTopology]
